spring:
  thymeleaf:
    mode: LEGACYHTML5

  datasource:
    url: jdbc:h2:mem:AZ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
logging:
  level:
    org:
      hibernate:
        type: trace
server:
  port: 8080
cursor:
  size: 10

